routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::group(['prefix' => 'paris', 'as' => 'paris.'], function () {
    Route::get('/generate', 'ParisController@index')->name('index');
    Route::post('/store','ParisController@store')->name('store');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ParisController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tirage;
use App\Models\TirageWinMac;
use Carbon\Carbon;
use http\Exception\BadMessageException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ParisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dt = Carbon::now();

        switch ($dt->dayOfWeek){
            case Carbon::MONDAY :
                $tirages = Tirage::where('jour','lundi')->first();
                break;
            case Carbon::TUESDAY:
                $tirages = Tirage::where('jour','mardi')->first();
                break;
            case Carbon::WEDNESDAY:
                $tirages = Tirage::where('jour','mercredi')->first();
                break;
            case Carbon::THURSDAY:
                $tirages = Tirage::where('jour','jeudi')->first();
                break;
            case Carbon::FRIDAY:
                $tirages = Tirage::where('jour','vendredi')->first();
                break;
            case Carbon::SATURDAY:
                $tirages = Tirage::where('jour','samedi')->first();
                break;
            case Carbon::SUNDAY:
                $tirages = Tirage::where('jour','dimanche')->first();
                break;
        }


        $tirages = $tirages->tirage;

        return view('paris.create',compact('tirages'));
    }


    public function generateParis(){
        $tirage = []; // est un tableau de 10
        $tirage_machine  = [];// est un tableau de 10
        $choix = array();
        $coef_PN = 40;
        $coef_1N = 11;
        $coef_2N = 240;
        $coef_3N = 2000;
        $coef_4N = 5000;
        $coef_5N = 40000;
        $coef_TURBO2 = 2400;
        $coef_TURBO3 = 2400;
        $coef_TURBO4 = 2400;
        $gain_user = '';
        $mise = '';
        $typedeparis ='';
        $typedeparis2 = '';
        $typedejeu ='';
        $doublechance ='';

        switch ($typedeparis) {
            case 'PN':
                if (!$doublechance) {
                    if ($choix[0] == $tirage[0]) {
                        $gain_user =
                            $coef_PN * $mise;
                    }else{
                        $gain_user = 0;
                    }
                } else {
                    if ($choix[0] == $tirage_machine[0]) {
                        $gain_user
                            = (($coef_PN * $mise) * 40) / 100;
                    } elseif ($choix[0] == $tirage[0]) {
                        $gain_user = (($coef_PN * $mise) * 60) / 100;
                    }
                }
                break;
            case '1N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) == 1) {
                        $gain_user = $coef_1N * $mise;
                    }else{
                        $gain_user = 0;
                    }
                }else {
                    $result_1 = array_intersect($choix, $tirage);
                    $result_2 = array_intersect($choix, $tirage_machine);

                    if (count($result_1) == 1) {
                        $gain_user
                            = (($coef_1N * $mise) * 60) / 100;
                    }else {
                        if (count($result_2) == 1) {
                            $gain_user
                                = (($coef_1N * $mise) * 40) / 100;
                        }else{
                            $gain_user = 0;
                        }
                    }

                }
                break;
            case '2N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) == 2) {
                        $gain_user = $coef_2N * $mise;
                    } else {
                        $gain_user = 0;
                    }
                } else {
                    $result_1 = array_intersect($choix, $tirage);
                    $result_2 = array_intersect($choix, $tirage_machine);

                    if (count($result_1) == 2) {
                        $gain_user
                            = (($coef_2N * $mise) * 60) / 100;
                    } else {
                        if (count($result_2) == 2) {
                            $gain_user
                                = (($coef_2N * $mise) * 40) / 100;
                        } else {
                            $gain_user = 0;
                        }
                    }
                }
                break;
            case '3N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) == 3) {
                        $gain_user = $coef_3N * $mise;
                    } else {
                        $gain_user = 0;
                    }
                } else {
                    $result_1 = array_intersect($choix, $tirage);
                    $result_2 = array_intersect($choix, $tirage_machine);

                    if (count($result_1) == 3) {
                        $gain_user
                            = (($coef_3N * $mise) * 60) / 100;
                    } else {
                        if (count($result_2) == 3) {
                            $gain_user
                                = (($coef_3N * $mise) * 40) / 100;
                        } else {
                            $gain_user = 0;
                        }
                    }
                }
                break;
            case '4N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) == 4) {
                        $gain_user = $coef_4N * $mise;
                    } else {
                        $gain_user = 0;
                    }
                } else {
                    $result_1 = array_intersect($choix, $tirage);
                    $result_2 = array_intersect($choix, $tirage_machine);

                    if (count($result_1) == 4) {
                        $gain_user
                            = (($coef_4N * $mise) * 60) / 100;
                    } else {
                        if (count($result_2) == 4) {
                            $gain_user
                                = (($coef_4N * $mise) * 40) / 100;
                        } else {
                            $gain_user = 0;
                        }
                    }
                }
                break;
            case '5N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) == 5) {
                        $gain_user = $coef_5N * $mise;
                    } else {
                        $gain_user = 0;
                    }
                } else {
                    $result_1 = array_intersect($choix, $tirage);
                    $result_2 = array_intersect($choix, $tirage_machine);

                    if (count($result_1) == 5) {
                        $gain_user
                            = (($coef_5N * $mise) * 60) / 100;
                    } else {
                        if (count($result_2) == 5) {
                            $gain_user
                                = (($coef_5N * $mise) * 40) / 100;
                        } else {
                            $gain_user = 0;
                        }
                    }
                }
                break;
            case 'PERM 2N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) > 1) {
                        $gain_user = ($coef_2N * count($result)) * $mise;
                    } else {
                        $gain_user = 0;
                    }
                }else{
                    $result_1 = array_intersect($choix, $tirage);
                    $result_2 = array_intersect($choix, $tirage_machine);

                    if (count($result_1) > 1) {
                        $gain_user
                            = (($coef_2N * $mise * count($result_1)) * 60) / 100;
                    } else {
                        if (count($result_2) > 1) {
                            $gain_user
                                = (($coef_2N * $mise* count($result_2)) * 40) / 100;
                        } else {
                            $gain_user = 0;
                        }
                    }
                }
                break;
            case 'PERM 3N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) > 2) {
                        $gain_user = ($coef_3N * count($result)) * $mise;
                    } else {
                        $gain_user = 0;
                    }
                } else {
                    $result_1 = array_intersect($choix, $tirage);
                    $result_2 = array_intersect($choix, $tirage_machine);

                    if (count($result_1) > 2) {
                        $gain_user
                            = (($coef_3N * $mise * count($result_1)) * 60) / 100;
                    } else {
                        if (count($result_2) > 2) {
                            $gain_user
                                = (($coef_3N * $mise * count($result_2)) * 40) / 100;
                        } else {
                            $gain_user = 0;
                        }
                    }
                }
                break;
            case 'PERM 4N':
                if (!$doublechance) {
                    $result = array_intersect($choix, $tirage);
                    if (count($result) > 3) {
                        $gain_user = ($coef_4N * count($result)) * $mise;
                    } else {

resources/views/paris/create.blade.php
@extends('layouts.master')

@section('title') Ecole @endsection

@section('subTitle') Creation @endsection

@section('css')
    <style>

        .choose_file{
            position:relative;
            display:inline-block;
            border-radius:8px;
            border:#ebebeb solid 1px;
            width:250px;
            padding: 4px 6px 4px 8px;
            font: normal 14px Myriad Pro, Verdana, Geneva, sans-serif;
            color: #7f7f7f;
            margin-top: 2px;
            background:white
        }
        .choose_file input[type="file"]{
            -webkit-appearance:none;
            position:absolute;
            top:0; left:0;
            opacity:0;
        }

    </style>
@endsection
@section('content')
    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <form action="{{ route('paris.store') }}" method="POST">
                    @csrf()
                <fieldset>
                    <legend>Mode</legend>
                    <select class="form-control" name="mode">
                        @foreach($tirages as $item)
                            <option value="{{$item['name']}}">{{ $item['name'] .' '. $item['heure'] }}</option>
                        @endforeach
                    </select>
                </fieldset>
                <fieldset>
                    <legend>
                        TIRAGE WINNER
                    </legend>
                    <div class="row">
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°1</label>
                                <div class="row">
                                    <input type="number" name="tirage_win[0]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°2</label>
                                <div class="row">
                                    <input type="number" name="tirage_win[1]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°3</label>
                                <div class="row">
                                    <input type="number" name="tirage_win[2]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°4</label>
                                <div class="row">
                                    <input type="number" name="tirage_win[3]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°5</label>
                                <div class="row">
                                    <input type="number" name="tirage_win[4]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>
                        TIRAGE MACHINE
                    </legend>
                    <div class="row">
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°1</label>
                                <div class="row">
                                    <input type="number" name="tirage_mac[0]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°2</label>
                                <div class="row">
                                    <input type="number" name="tirage_mac[1]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°3</label>
                                <div class="row">
                                    <input type="number" name="tirage_mac[2]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°4</label>
                                <div class="row">
                                    <input type="number" name="tirage_mac[3]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="name">N°5</label>
                                <div class="row">
                                    <input type="number" name="tirage_mac[4]" class="form-control" id="nometab" required>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <button id="save" type="submit" class="btn btn-info btn-icon-split mt-3">
                    <span class="icon text-white-50">
                        <i class="feather icon-save"></i>
                    </span>
                    <span class="text">Valider</span>
                </button>
                </form>
            </div>
        </div>
    </section>

@endsection
@section('js')
    <script type="text/javascript" src="{{asset('webcamjs/webcam.min.js')}}"></script>
    <!-- Code to handle taking the snapshot and displaying it locally -->
    <script language="JavaScript">

        // Configure a few settings and attach camera
        function configure(){
            $('#my_camera').attr('style',"");
            // $('#my_camera1').attr('style',"display:none;");
            Webcam.set({
                width: 320,
                height: 240,
                image_format: 'jpeg',
                jpeg_quality: 300,
            });
            Webcam.attach('#my_camera');
        }
        // A button for taking snaps
        // preload shutter audio clip
        var shutter = new Audio();
        shutter.autoplay = false;
        shutter.src = navigator.userAgent.match(/Firefox/) ? "{{ asset('sounds/shutter.ogg') }}" : "{{ asset('sounds/shutter.mp3') }}";

        function take_snapshot() {
            $('#my_camera').attr('style',"display:none;");
            // play sound effect
            shutter.play();
            // take snapshot and get image data
            Webcam.snap( function(data_uri) {
                //console.log(data_uri);
                // display results in page
                //$('#fileInput').val(data_uri);
                document.getElementById('resultat').innerHTML = `<input name="photo" id="fileInput" value="${data_uri}" type="hidden" style="display: none;"/>`;//'<img id="imageprev" src="'+data_uri+'"/>';
                document.getElementById('my_camera1').innerHTML = `<img id="imageprev" src="${data_uri}"/>`;//;
            } );
            Webcam.reset();
        }

        function saveSnap(){
            // Get base64 value from <img id='imageprev'> source
            var base64image =  document.getElementById("imageprev").src;
            console.log(base64image);
            Webcam.uploadbase64image( base64image, 'upload.php', function(code, text) {
                console.log('Save successfully');
                //console.log(text);
            });
        }
    </script>
    <script>
        function chooseFile() {
            $("#fileInput").click();
        }
    </script>
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image_id').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#fileInput").change(function(){
            readURL(this);
        });
    </script>
@endsection

resources/views/paris/edit.blade.php
@extends('layouts.master')

@section('title') Ecole @endsection

@section('subTitle') Creation @endsection

@section('css')
    <style>

        .choose_file{
            position:relative;
            display:inline-block;
            border-radius:8px;
            border:#ebebeb solid 1px;
            width:250px;
            padding: 4px 6px 4px 8px;
            font: normal 14px Myriad Pro, Verdana, Geneva, sans-serif;
            color: #7f7f7f;
            margin-top: 2px;
            background:white
        }
        .choose_file input[type="file"]{
            -webkit-appearance:none;
            position:absolute;
            top:0; left:0;
            opacity:0;
        }

    </style>
@endsection
@section('content')
    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                {{ Form::model($ecole,['route'=>'ecole.update', 'files'=>true]) }}
                {{Form::hidden('_method','PUT')}}
                {{ Form::hidden('id', $ecole->id) }}
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label for="name">NOM ETABLISSEMENT</label>
                            <input type="text" name="nometab" value="{{$ecole->nometab}}" class="form-control" id="nometab" required>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="slug">CODE</label>
                            <input type="text" name="code" value="{{$ecole->code}}"  class="form-control" id="code"  required>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="slug">GENRE</label>
                            <input type="text" name="genre"  value="{{$ecole->genre}}"  class="form-control" id="genre"  required>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="slug">DREN</label>
                            <input type="text" name="dren" value="{{$ecole->dren}}"  class="form-control" id="dren" required>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="slug">COMMUNE</label>
                            <input type="text" name="commune"  value="{{$ecole->commune}}" class="form-control" id="commune" required>
                        </div>
                    </div>
                    <div class="col-4">
                        <div class="form-group">
                            <label for="slug">CYCLE</label>
                            <input type="text" name="cycle" value="{{$ecole->cycle}}"  class="form-control" id="cycle" required>
                        </div>
                    </div>
                </div>

                <button id="save" type="submit" class="btn btn-info btn-icon-split mt-3">
                    <span class="icon text-white-50">
                        <i class="feather icon-save"></i>
                    </span>
                    <span class="text">Modifier</span>
                </button>
                {{ Form::close() }}
            </div>
        </div>
    </section>

@endsection

resources/views/paris/index.blade.php
@extends('layouts.master')

@section('title') Etablissement @endsection

@section('subTitle') Tous @endsection


@section('content')

    <section class="card">
        <div class="card-header">
            <h4 class="card-title"></h4>
        </div>
        <div class="card-content">

            <div class="card-body">

                <div class="mb-3">
                    <a class="btn btn-primary" href="{{ route('ecole.create') }}">
                        <span><i class="feather icon-plus"></i>Enregistrer une ecole</span>
                    </a>
                </div>

                <div class="table-responsive-sm">
                    <table class="table table-hover table-striped">
                        <thead>
                        <tr>
                          {{--  @if(auth()->user()->hasRole('Admin'))
                                <th>Etablissement</th>
                            @endif--}}
                            <th>Nom etablissement</th>
                            <th>Code</th>
                            <th>Dren</th>
                            <th>Commune</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($ecoles as $item)
                            <tr>
                               {{-- @if(auth()->user()->hasRole('Admin'))
                                    <td> <strong>{{ $item->ecole->nometab }}</strong></td>
                                @endif--}}
                                <td> {{ $item->nometab }}</td>
                                <td> {{ $item->code }}</td>
                                <td> {{ $item->dren }}</td>
                                <td> {{ $item->commune }}</td>

                                <td class="float-right">
                                    {{--{{route('imprime.fiche',$item->id)}}--}}
                                   {{-- <a href="#"
                                       class="btn btn-icon btn-icon rounded-circle btn-flat-primary mr-0 waves-effect waves-light">
                                        <i class="feather icon-printer"></i>
                                    </a>
                                    <button type="button"
                                            class="btn btn-icon btn-icon rounded-circle btn-success mr-0 waves-effect waves-light">
                                        <i class="feather icon-target"></i>
                                    </button>--}}
                                    <a href="{{ route('ecole.edit',$item->id) }}"
                                       class="btn btn-icon btn-icon rounded-circle btn-primary mr-0 waves-effect waves-light">
                                        <i class="feather icon-edit"></i>
                                    </a>
                                    <button type="button"
                                            data-id="{{$item->id}}"
                                            data-toggle="modal"
                                            data-target="#deletedEcole"
                                            class="btn btn-icon btn-icon rounded-circle btn-danger mr-0 waves-effect waves-light">
                                        <i class="feather icon-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                        @if(count($ecoles) < 1)
                            <tr>
                                <td colspan="10" class="text-center">Pas d'eleve trouvé !</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center mt-2">
                        {{ $ecoles->links() }}
                    </ul>
                </nav>
            </div>
        </div>
    </section>
    <div class="modal modal-danger fade" id="deletedEcole" tabindex="-1" role="dialog" aria-labelledby="myModalLabel16" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header bg-danger white">
                    <h4 class="modal-title" id="myModalLabel16">Confirmation la supprimer</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {{ Form::open(['route'=>'ecole.delete', 'files'=>true , 'methode' => 'POST']) }}

                    {{method_field('delete')}}
                    {{csrf_field()}}
                    <div class="modal-body">
                        <p class="text-center">
                            Êtes-vous sûr de vouloir le supprimer ?
                        </p>
                        <input type="hidden" name="id" id="eleve_id" value="">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">Non, Annuler</button>
                        <button type="submit" class="btn btn-warning">Oui, Supprimer</button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>

@endsection
@section('js')
    <script>
        $('#deletedEcole').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var id = button.data('id');
            var modal = $(this);
            modal.find('.modal-body #eleve_id').val(id);
        });
    </script>
@endsection